[default]
workshop = [
    "450814997",  # CBA_A3
    "463939057", # ACE
    "3499977893", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []
