#define CINEMA_BORDER_DEFAULT_DURATION 8

#define CINEMA_BORDER_LETTERBOX_OFFSET 0.1
#define CINEMA_BORDER_LETTERBOX_HEIGHT (0.125 * safeZoneH)

#define IDC_CINEMA_BORDER_TITLE 731101
#define IDC_CINEMA_BORDER_LETTERBOX_TOP 731102
#define IDC_CINEMA_BORDER_LETTERBOX_BOTTOM 731103
